apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-users-group6263
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-users-group6263
  template:
    metadata:
      labels:
        app: ms-users-group6263
    spec:
      containers:
        - name: ms-users-group6263
          image: 057196872298.dkr.ecr.us-east-2.amazonaws.com/ms-users-group6263:latest
          ports:
            - containerPort: 8084